import { Injectable } from '@angular/core';
import { Game } from '../models/game';

@Injectable({
  providedIn: 'root'
})
export class GameService {
  private games = new Array<Game>();

  private autoGeneratedId = 0;

  constructor() { }

  // CRUD

  create(game: Game): void {
    game.id = this.autoGeneratedId;
    this.games.push(game);
    this.autoGeneratedId++;
  }

  read(): Array<Game> {
    return this.games;
  }

  update(game: Game): void {
    for (let i = 0; this.games.length; i++) {
      const g = this.games[i];
      if (g.id === game.id ) {
        this.games[i] = game;
        break;
      }
    }
  }

  delete(id: number): void {
    for (let i = 0; this.games.length; i++) {
      const game = this.games[i];
      if (id === game.id ) {
        this.games.splice(i, 1);
        break;
      }
    }
  }

}
